name: Dispatch-Add-VPM-Repository
on:
    release:
      types: [published]
    workflow_dispatch:

jobs:
  SendVpmRS64Net:
    runs-on: ubuntu-latest
    steps:
      - name: Debug payload information
        run: |
          echo "=== Debug Information ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Release tag name: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"
          echo "Repository: AvatarPosingStationUtilities"
          echo "Target repository: kurotori4423/vpm.kurotori4423"
          echo "Client payload: {\"repository\": \"AvatarPosingStationUtilities\", \"tag\": \"${{ github.event.release.tag_name }}\"}"
          echo "========================="
      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.VPM_REPO_TOKEN }}
          repository: kurotori4423/vpm.kurotori4423
          event-type: add_new_version
          client-payload: '{"repository": "AvatarPosingStationUtilities", "tag": "${{ github.event.release.tag_name }}"}'